import os



def get_token():
    '''
    TOKEN generated by @BotFather on Telegram

    This TOKEN should correspond to @sternenkarte_bot created by:
    Giuseppe Gomez, Edgar Torres y Juan Padilla
    '''

    # The token can be kept as an env var
    TOKEN = os.environ.get('TELEGRAM_TOKEN')

    if TOKEN is None:
        TOKEN = input('Enter the bot token: ')

    return TOKEN